apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-setup
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/scabarrus/argocd
    path: setup/config/project
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
