apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: keycloak
  source:
    repoURL: https://github.com/scabarrus/argocd.git
    path: apps/helm/keycloak-removed
    targetRevision: main
    helm:
      fileParameters:
      - path: ../../config/keycloak/values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: keycloak
